### ISSUE TITLE
Fix linter

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#86]
I'm sorry it has come to that, but do you mind fixing the linter issues @thomas-senechal ? There is probably tools to (partly) automate the process.

**Comment by thomas-senechal** [comment]
Found this formatter: https://github.com/dzhu/rstfmt 
But it seems to only supports one file at the time and doesn't supports the `index` directive:

```shell
$ rstfmt --width 120 technical-doc/api.rst
:1: (ERROR/3) Unknown directive type "index".

.. index:: api, JSON-RPC

Traceback (most recent call last):
  File "/opt/homebrew/bin/rstfmt", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/rstfmt/__main__.py", line 95, in main
    do_file(args, path, misformatted)
  File "/opt/homebrew/lib/python3.10/site-packages/rstfmt/__main__.py", line 31, in do_file
    doc = rstfmt.parse_string(inp)
  File "/opt/homebrew/lib/python3.10/site-packages/rstfmt/rstfmt.py", line 750, in parse_string
    parser.parse(s, doc)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/parsers/rst/__init__.py", line 183, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    return self.unknown_directive(type_name)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2280, in unknown_directive
    error = self.reporter.error(
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/utils/__init__.py", line 231, in error
    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/rstfmt/rstfmt.py", line 274, in system_message
    msg = super().system_message(level, message, *children, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/docutils/utils/__init__.py", line 197, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: :1: (ERROR/3) Unknown directive type "index".

.. index:: api, JSON-RPC
```

I will see if something else is available. If not, I will use this one.

**Comment by thomas-senechal** [comment]
I found this formatter: https://github.com/LilSpazJoekp/docstrfmt 
Which also doesn't supports the `index` directive.
